CREATE DATABASE IF NOT EXISTS `orders`;
GRANT ALL PRIVILEGES ON `orders`.* TO 'atlas'@'%' WITH GRANT OPTION;

CREATE DATABASE IF NOT EXISTS `products`;
GRANT ALL PRIVILEGES ON `products`.* TO 'atlas'@'%' WITH GRANT OPTION;

CREATE DATABASE IF NOT EXISTS `reviews`;
GRANT ALL PRIVILEGES ON `reviews`.* TO 'atlas'@'%' WITH GRANT OPTION;

CREATE DATABASE IF NOT EXISTS `users`;
GRANT ALL PRIVILEGES ON `users`.* TO 'atlas'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
